<h1>Prijava korisnika</h1>
<form action="<?php echo $router->pathFor('prijava'); ?>" method="POST">
	<label for="email">Email</label>
	<input type="email" name="email" id="email" placeholder="email" autofocus value="<?php echo isset($staro['email']) ? $staro['email'] : ''; ?>">
	<?php
	if(isset($greske['email'])) {
		echo '<span style="color: red; font-size: 12px;">' . $greske['email'] . '</span>';
	}
	?><br>
	<label for="lozinka">Lozinka</label>
	<input type="password" name="lozinka" id="lozinka" placeholder="lozinka">
	<?php
	if(isset($greske['lozinka'])) {
		echo '<span style="color: red; font-size: 12px;">' . $greske['lozinka'] . '</span>';
	}
	?><br><br>
	<input type="submit" value="Prijavi se"> &nbsp;&nbsp;&nbsp;&nbsp;
	<a href="<?php echo $router->pathFor('pocetna'); ?>">Otkazi</a>
	<?php echo $csrf ? $csrf : '' ?>
</form>