<h1>Promena lozinke korisnika</h1>
<form action="<?php echo $router->pathFor('korisnik.promena-lozinke'); ?>" method="POST">
	<label for="lozinka">Nova lozinka</label>
	<input type="password" name="nova_lozinka" id="nova_lozinka" placeholder="Nova lozinka" autofocus>
	<?php
	if(isset($greske['nova_lozinka'])) {
		echo '<span style="color: red; font-size: 12px;">' . $greske['nova_lozinka'] . '</span>';
	}
	?><br>
	<label for="lozinka">Trenutna lozinka</label>
	<input type="password" name="trenutna_lozinka" id="trenutna_lozinka" placeholder="Trenutna lozinka" autofocus>
	<?php
	if(isset($greske['trenutna_lozinka'])) {
		echo '<span style="color: red; font-size: 12px;">' . $greske['trenutna_lozinka'] . '</span>';
	}
	?><br><br>
	<input type="submit" value="Promeni lozinku"> &nbsp;&nbsp;&nbsp;&nbsp;
	<a href="<?php echo $router->pathFor('korisnik.pocetna'); ?>">Otkazi</a>
	<?php echo $csrf ? $csrf : '' ?>
</form>